version: '3.9'

services:
  tk-api:
    build: .
    container_name: tk_api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
    volumes:
      - .:/app

  db:
    image: postgres:14
    container_name: tk_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: tk_rabbitmq
    restart: always
    ports:
      - "5672:5672"   # Porta do RabbitMQ
      - "15672:15672" # UI de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: "0.5"  # Usa no máximo 50% da RAM
    volumes:
      - .:/app
  
  celery_worker:
    build: .
    container_name: tk_celery_worker
    command: celery -A app.tasks.celery_worker worker --loglevel=info --concurrency=2 --prefetch-multiplier=1 --max-tasks-per-child=100
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - tk-api
    restart: always  # 🔁 Reinicia se travar


volumes:
  postgres_data:
